# Generated by Django 3.2.16 on 2023-06-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='room_no',
            field=models.IntegerField(null=True),
        ),
    ]
