# Generated by Django 3.2.16 on 2023-06-23 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_manage', '0004_auto_20230622_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='admission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital_manage.admission'),
        ),
    ]
