# Generated by Django 3.2.16 on 2023-06-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_manage', '0005_alter_medicalrecord_admission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='discharge_date',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='room_no',
        ),
    ]
