# Generated by Django 3.2.16 on 2023-06-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_manage', '0006_auto_20230626_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='room',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
